### ISSUE TITLE
موضع نقطة التاء المربوطة

### ISSUE THREAD

**Issue by Abdulmoneim** [alif-type/rana-kufi#9]
السلام عليكم ورحمة الله وبركاته

عند استخذام حرف التاء المربوطة المحلاة يكون هناك تداخل بين نقاط التاء المربوطة والحلية
![image](https://user-images.githubusercontent.com/6818164/73139370-774fd900-407e-11ea-8bb9-f31f46b11313.png)

شكراً لجهودكم

**Comment by khaledhosny** [comment]
في هذه الحالة لا أنصح باستخدام هذه الهاء مع التاء المربوطة.
